#!/bin/bash
# Tauri local docs update script (with staleness check)
# Usage: bash <skill-directory>/references/update.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TAURI_REF_DIR="$SCRIPT_DIR"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LAST_UPDATED="$TAURI_REF_DIR/.last_updated"
STALE_SECONDS=43200  # 12 hours

# Staleness check
if [ -f "$LAST_UPDATED" ]; then
  last=$(cat "$LAST_UPDATED")
  now=$(date +%s)
  elapsed=$(( now - last ))
  if [ "$elapsed" -lt "$STALE_SECONDS" ]; then
    echo "Tauri docs up to date (updated $(( elapsed / 3600 ))h $(( (elapsed % 3600) / 60 ))m ago)"
    exit 0
  fi
fi

echo "=== Updating Tauri local docs ==="

# If cloned directories don't exist, abort without recording .last_updated
if [ ! -d "$TAURI_REF_DIR/tauri-docs" ] || [ ! -d "$TAURI_REF_DIR/plugins-workspace" ]; then
  echo "⚠ Local docs not cloned. Run the Local Docs Setup in SKILL.md first."
  exit 1
fi

echo "[1/4] tauri-docs (v2)..."
cd "$TAURI_REF_DIR/tauri-docs" && git pull origin v2 2>&1

echo "[2/4] plugins-workspace (v2)..."
cd "$TAURI_REF_DIR/plugins-workspace" && git pull origin v2 2>&1

echo "[3/4] Generating auto-index..."
INDEX_FILE="$TAURI_REF_DIR/auto-index.md"
DOCS_DIR="$TAURI_REF_DIR/tauri-docs/src/content/docs"
PLUGINS_DIR="$TAURI_REF_DIR/plugins-workspace/plugins"

{
  echo "# Tauri Docs Auto-Index"
  echo "# Auto-generated by update.sh — DO NOT EDIT MANUALLY"
  echo "# Generated: $(date '+%Y-%m-%d %H:%M')"
  echo ""
  echo "## Official Docs"
  echo ""
  echo "| Path | Title | Description |"
  echo "|------|-------|-------------|"

  if [ -d "$DOCS_DIR" ]; then
    find "$DOCS_DIR" \( -name "*.mdx" -o -name "*.md" \) | sort | while read -r file; do
      rel="${file#$DOCS_DIR/}"
      title=$(awk '/^---/{if(n++) exit} /^title:/{sub(/^title: */, ""); gsub(/["'"'"']/, ""); gsub(/^ +| +$/, ""); print}' "$file")
      desc=$(awk '/^---/{if(n++) exit} /^description:/{sub(/^description: */, ""); gsub(/["'"'"']/, ""); gsub(/^ +| +$/, ""); print}' "$file")
      [ -n "$title" ] && echo "| $rel | $title | $desc |"
    done
  fi

  echo ""
  echo "## Plugin READMEs"
  echo ""
  echo "| Plugin | Path |"
  echo "|--------|------|"

  if [ -d "$PLUGINS_DIR" ]; then
    find "$PLUGINS_DIR" -maxdepth 2 -name "README.md" | sort | while read -r file; do
      rel="${file#$TAURI_REF_DIR/}"
      plugin=$(echo "$file" | sed 's|.*/plugins/||; s|/README.md||; s|/.*||')
      echo "| $plugin | $rel |"
    done
  fi
} > "$INDEX_FILE"

line_count=$(wc -l < "$INDEX_FILE")
echo "  → auto-index.md generated (${line_count} lines)"

echo "[4/4] Validating Quick Lookup table..."
SKILL_MD="$SKILL_DIR/SKILL.md"
broken=0
# Extract .mdx paths from SKILL.md table and verify they exist
paths=$(grep '^|' "$SKILL_MD" | grep -oE '`[^`]+\.mdx`' | tr -d '`' | grep -v '<')
for rel_path in $paths; do
  if [ ! -f "$DOCS_DIR/$rel_path" ]; then
    echo "  ⚠ BROKEN: $rel_path"
    broken=$((broken + 1))
  fi
done
if [ "$broken" -gt 0 ]; then
  echo "  ⚠ ${broken} path(s) broken. Check the Quick Lookup table in SKILL.md."
else
  echo "  ✓ All Quick Lookup paths valid"
fi

date +%s > "$LAST_UPDATED"
echo "=== Done ==="
